export enum LocationUtilitaireEn {
    VoitureSociete = 'Location voiture société',
    Utilitaire3m3 = 'Location utilitaire 3m3',
    Utilitaire4m3 = 'Location utilitaire 4m3',
    Utilitaire6m3 = 'Location utilitaire 6m3',
    Utilitaire7m3 = 'Location utilitaire 7m3',
    Utilitaire8m3 = 'Location utilitaire 8m3',
    Utilitaire12m3 = 'Location utilitaire 12m3',
    Utilitaire15m3 = 'Location utilitaire 15m3',
    Utilitaire20m3 = 'Location utilitaire 20m3',
    Utilitaire20m3AvecHayon = 'Location utilitaire 20m3 avec hayon',
    Utilitaire25m3 = 'Location utilitaire 25m3',
    Utilitaire30m3 = 'Location utilitaire 30m3',
    PoidsLourd = 'Location poids lourd',
    BenneBasculante = 'Location benne basculante',
    CamionBennePaysagiste = 'Location camion benne paysagiste',
    CamionPlateauRidelles = 'Location camion plateau ridelles',
    CamionPupitre = 'Location camion pupitre',
    CamionPlateau = 'Location camion plateau',
    RemorquePorteVoiture = 'Location remorque porte voiture',
    RemorquePorteMotoOuQuad = 'Location remorque porte moto ou quad'
}
