export enum LocationUtilitaireEn {
    VoitureSociete = 'voiture_société',
    Utilitaire3m3 = 'utilitaire_3m3',
    Utilitaire4m3 = 'utilitaire_4m3',
    Utilitaire6m3 = 'utilitaire_6m3',
    Utilitaire7m3 = 'utilitaire_7m3',
    Utilitaire8m3 = 'utilitaire_8m3',
    Utilitaire12m3 = 'utilitaire_12m3',
    Utilitaire15m3 = 'utilitaire_15m3',
    Utilitaire20m3 = 'utilitaire_20m3',
    Utilitaire20m3AvecHayon = 'utilitaire_20m3_avec_hayon',
    Utilitaire25m3 = 'utilitaire_25m3',
    Utilitaire30m3 = 'utilitaire_30m3',
    PoidsLourd = 'poids_lourd',
    BenneBasculante = 'benne_basculante',
    CamionBennePaysagiste = 'camion_benne_paysagiste',
    CamionPlateauRidelles = 'camion_plateau_ridelles',
    CamionPupitre = 'camion_pupitre',
    CamionPlateau = 'camion_plateau',
    RemorquePorteVoiture = 'remorque_porte_voiture',
    RemorquePorteMotoOuQuad = 'remorque_porte_moto_ou_quad'
}
