export enum LocationUtilitaireEn {
    voiture_société = 'Location voiture société',
    utilitaire_3m3 = 'Location utilitaire 3m3',
    utilitaire_4m3 = 'Location utilitaire 4m3',
    utilitaire_6m3 = 'Location utilitaire 6m3',
    utilitaire_7m3 = 'Location utilitaire 7m3',
    utilitaire_8m3 = 'Location utilitaire 8m3',
    Utilitaire_12m3 = 'Location utilitaire 12m3',
    Utilitaire_15m3 = 'Location utilitaire 15m3',
    Utilitaire_20m3 = 'Location utilitaire 20m3',
    utilitaire_20m3_avec_hayon = 'Location utilitaire 20m3 avec hayon',
    utilitaire_25m3 = 'Location utilitaire 25m3',
    utilitaire_30m3 = 'Location utilitaire 30m3',
    poids_lourd = 'Location poids lourd',
    benne_basculante = 'Location benne basculante',
    camion_benne_paysagiste = 'Location camion benne paysagiste',
    camion_plateau_ridelles = 'Location camion plateau ridelles',
    camion_pupitre = 'Location camion pupitre',
    camion_plateau = 'Location camion plateau',
    remorque_porte_voiture = 'Location remorque porte voiture',
    remorque_porte_moto_ou_quad = 'Location remorque porte moto ou quad'
}
